import type { FormSchema } from './schema'

/**
 * Formulár 2: Žiadosť o vydanie potvrdenia o veku stavby a čestné prehlásenie.
 * Zdroj: docs/forms/formular_obec_Bernolakovo.pdf, strany 2 a 3.
 */
export const vekStavbyForm: FormSchema = {
  id: 'potvrdenie-vek-stavby',
  nazov: 'Žiadosť o vydanie potvrdenia o veku stavby',
  kratkyPopis:
    'Potvrdenie o roku, v ktorom bola stavba daná do užívania. Býva potrebné pre znalecký posudok.',
  kategoria: 'Stavby a pozemky',
  poplatokEur: 0,
  poplatokPoznamka: 'Bez správneho poplatku.',
  odhadovanyCasMin: 10,
  pravnyZaklad: 'zákon č. 71/1967 Zb. o správnom konaní',
  adresat: 'Obecný úrad',
  pdfNazov: 'ziadost-o-potvrdenie-o-veku-stavby',
  infoPoznamka:
    'Potvrdenie zasielame na adresu na doručenie alebo si ho môžete prevziať osobne na úrade.',
  sections: [
    {
      id: 'ziadatel',
      title: 'Žiadateľ',
      description: 'Meno a priezvisko alebo názov firmy a adresa na doručenie.',
      fields: [
        {
          id: 'typOsoby',
          label: 'Žiadam ako',
          type: 'radio',
          required: true,
          colSpan: 2,
          options: [
            { value: 'fyzicka', label: 'Fyzická osoba' },
            { value: 'pravnicka', label: 'Právnická osoba' },
          ],
        },
        {
          id: 'nazovFirmy',
          label: 'Názov firmy',
          type: 'text',
          required: true,
          colSpan: 2,
          visibleIf: { field: 'typOsoby', equals: 'pravnicka' },
        },
        {
          id: 'ico',
          label: 'IČO',
          type: 'text',
          required: true,
          validate: 'ico',
          visibleIf: { field: 'typOsoby', equals: 'pravnicka' },
        },
        { id: 'titul', label: 'Titul', type: 'text', autofillFrom: 'resident.titul' },
        {
          id: 'meno',
          label: 'Meno',
          type: 'text',
          required: true,
          autofillFrom: 'resident.meno',
        },
        {
          id: 'priezvisko',
          label: 'Priezvisko',
          type: 'text',
          required: true,
          autofillFrom: 'resident.priezvisko',
        },
        {
          id: 'adresaDorucenia',
          label: 'Adresa na doručenie',
          type: 'address',
          required: true,
          colSpan: 2,
        },
        {
          id: 'telefon',
          label: 'Telefón',
          type: 'text',
          required: true,
          validate: 'telefon',
          autofillFrom: 'resident.telefon',
        },
        {
          id: 'email',
          label: 'E-mail',
          type: 'text',
          validate: 'email',
          helper: 'Na e-mail vám pošleme informáciu o vybavení žiadosti.',
          autofillFrom: 'resident.email',
        },
        {
          id: 'maZastupcu',
          label: 'Žiadosť podáva splnomocnený zástupca',
          type: 'checkbox',
          colSpan: 2,
        },
        {
          id: 'zastupca',
          label: 'Meno a priezvisko splnomocneného zástupcu',
          type: 'text',
          required: true,
          colSpan: 2,
          helper: 'Zástupca koná v zmysle plnej moci.',
          visibleIf: { field: 'maZastupcu', isTruthy: true },
        },
      ],
    },
    {
      id: 'ucel',
      title: 'Účel potvrdenia',
      fields: [
        {
          id: 'ucel',
          label: 'Potvrdenie potrebujem',
          type: 'radio',
          required: true,
          colSpan: 2,
          options: [
            { value: 'znalecky_posudok', label: 'Pre vypracovanie znaleckého posudku' },
            { value: 'iny', label: 'Z iného dôvodu' },
          ],
        },
        {
          id: 'inyDovod',
          label: 'Uveďte dôvod',
          type: 'textarea',
          required: true,
          colSpan: 2,
          maxLength: 400,
          visibleIf: { field: 'ucel', equals: 'iny' },
        },
      ],
    },
    {
      id: 'stavba',
      title: 'Stavba',
      description: 'Údaje o stavbe, ku ktorej potvrdenie žiadate.',
      fields: [
        {
          id: 'nehnutelnost',
          label: 'Vyberte nehnuteľnosť',
          type: 'propertyPicker',
          colSpan: 2,
          helper: 'Údaje o stavbe doplníme z vašej nehnuteľnosti. Môžete ich upraviť.',
        },
        {
          id: 'nazovStavby',
          label: 'Názov stavby',
          type: 'text',
          required: true,
          colSpan: 2,
          placeholder: 'Rodinný dom',
          autofillFrom: 'property.nazovStavby',
        },
        {
          id: 'ulica',
          label: 'Ulica',
          type: 'text',
          required: true,
          autofillFrom: 'property.adresa.ulica',
        },
        {
          id: 'katastralneUzemie',
          label: 'Katastrálne územie',
          type: 'select',
          required: true,
          optionsFromTenant: 'katastralneUzemia',
          autofillFrom: 'property.katastralneUzemie',
        },
        {
          id: 'parcelaCislo',
          label: 'Parcela č.',
          type: 'text',
          required: true,
          autofillFrom: 'property.parcelaCislo',
        },
        {
          id: 'cisloLv',
          label: 'Číslo listu vlastníctva',
          type: 'text',
          required: true,
          autofillFrom: 'property.cisloLv',
          helper: 'Číslo LV nájdete na katasterportal.sk.',
        },
        {
          id: 'supisneCislo',
          label: 'Súpisné číslo',
          type: 'text',
          required: true,
          autofillFrom: 'property.adresa.supisneCislo',
        },
      ],
    },
    {
      id: 'uzivanie',
      title: 'Uvedenie do užívania',
      fields: [
        {
          id: 'obdobieUzivania',
          label: 'Stavba bola daná do užívania',
          type: 'radio',
          required: true,
          colSpan: 2,
          options: [
            {
              value: 'po_1976',
              label: 'Po 1. 1. 1976',
              helper: 'Priložte kolaudačné rozhodnutie.',
            },
            {
              value: 'pred_1976',
              label: 'Pred 1. 1. 1976',
              helper: 'Vyplníte čestné prehlásenie.',
            },
          ],
        },
        {
          id: 'rokUzivania',
          label: 'Rok, v ktorom bola stavba daná do užívania',
          type: 'year',
          required: true,
          validate: 'rok',
          placeholder: '1974',
          autofillFrom: 'property.rokKolaudacie',
        },
        {
          id: 'kolaudacneRozhodnutie',
          label: 'Právoplatné kolaudačné rozhodnutie',
          type: 'file',
          required: true,
          colSpan: 2,
          maxSuborov: 3,
          maxVelkostMb: 5,
          visibleIf: { field: 'obdobieUzivania', equals: 'po_1976' },
          chybaText: 'Pri stavbe danej do užívania po 1. 1. 1976 je kolaudačné rozhodnutie povinné.',
        },
      ],
    },
    {
      id: 'cestnePrehlasenie',
      title: 'Čestné prehlásenie',
      description:
        'Pri stavbách daných do užívania pred 1. 1. 1976 nahrádza čestné prehlásenie kolaudačné rozhodnutie.',
      visibleIf: { field: 'obdobieUzivania', equals: 'pred_1976' },
      fields: [
        {
          id: 'cpMenoPriezvisko',
          label: 'Meno a priezvisko',
          type: 'text',
          required: true,
          colSpan: 2,
        },
        {
          id: 'cpRodneCislo',
          label: 'Rodné číslo',
          type: 'text',
          required: true,
          validate: 'rodneCislo',
          placeholder: '940215/6789',
          helper: 'Rodné číslo zobrazujeme zakryté, v plnom tvare ho vidí len úrad.',
          autofillFrom: 'resident.rodneCislo',
        },
        {
          id: 'cpCisloOp',
          label: 'Číslo občianskeho preukazu',
          type: 'text',
          required: true,
          validate: 'cisloOp',
          placeholder: 'AB 123456',
        },
        {
          id: 'cpTrvaleBytom',
          label: 'Trvale bytom',
          type: 'text',
          required: true,
          colSpan: 2,
        },
        {
          id: 'cpRokUzivania',
          label: 'Stavba bola daná do užívania v roku',
          type: 'year',
          required: true,
          validate: 'rok',
        },
        {
          id: 'cpRokRekonstrukcie',
          label: 'Rekonštruovaná v roku',
          type: 'year',
          validate: 'rok',
          helper: 'Vyplňte, ak bola stavba rekonštruovaná.',
        },
        { id: 'cpParcela', label: 'Na pozemku parc. č.', type: 'text', required: true },
        {
          id: 'cpKatastralneUzemie',
          label: 'V katastrálnom území',
          type: 'select',
          required: true,
          optionsFromTenant: 'katastralneUzemia',
          autofillFrom: 'tenant.nazovKratky',
        },
        {
          id: 'cpStavebnikomBol',
          label: 'Stavebníkom bol',
          type: 'text',
          required: true,
          colSpan: 2,
        },
        {
          id: 'cpPoucenie',
          label: 'Poučenie',
          type: 'info',
          colSpan: 2,
          text: 'Tieto údaje sú pravdivé a úplné. Som si vedomý právnych následkov nepravdivého čestného vyhlásenia, na ktoré ma upozornil overujúci orgán podľa § 39 ods. 3 zák. č. 71/1967 Zb. Všetky uvedené osobné údaje môžu byť použité len pre účely vyhotovenia potrebných listín a nemôžu byť poskytnuté na iné účely.',
        },
        {
          id: 'cpPotvrdenie',
          label: 'Potvrdzujem čestné prehlásenie v uvedenom znení.',
          type: 'consent',
          required: true,
          colSpan: 2,
          chybaText: 'Bez potvrdenia čestného prehlásenia žiadosť odoslať nevieme.',
        },
      ],
    },
    {
      id: 'vlastnictvo',
      title: 'Stavebník a vlastník',
      fields: [
        {
          id: 'stavebnikomBoli',
          label: 'Stavebníkom boli',
          type: 'text',
          required: true,
          colSpan: 2,
        },
        {
          id: 'vlastnikomJe',
          label: 'Vlastníkom je',
          type: 'text',
          required: true,
          colSpan: 2,
        },
        {
          id: 'ziadatelJeStavebnik',
          label: 'Žiadateľ je zároveň stavebníkom budovy',
          type: 'checkbox',
          colSpan: 2,
          helper: 'Ak nie ste stavebníkom, priložte nadobúdací doklad.',
        },
      ],
    },
    {
      id: 'prilohy',
      title: 'Prílohy',
      description: 'Nahrajte doklady k žiadosti. Prijímame formáty PDF, JPG a PNG.',
      fields: [
        {
          id: 'geometrickyPlan',
          label: 'Geometrický plán ku stavbe',
          type: 'file',
          colSpan: 2,
          maxSuborov: 2,
          maxVelkostMb: 5,
        },
        {
          id: 'snimkaKatastralnejMapy',
          label: 'Snímka z katastrálnej mapy',
          type: 'file',
          colSpan: 2,
          maxSuborov: 2,
          maxVelkostMb: 5,
        },
        {
          id: 'nadobudaciDoklad',
          label:
            'Kúpnopredajná zmluva, osvedčenie o dedičstve alebo darovacia zmluva',
          type: 'file',
          required: true,
          colSpan: 2,
          maxSuborov: 3,
          maxVelkostMb: 5,
          helper: 'Predkladá žiadateľ, ktorý nie je stavebníkom budovy.',
          visibleIf: { field: 'ziadatelJeStavebnik', isTruthy: false },
        },
      ],
    },
    {
      id: 'potvrdenie',
      title: 'Potvrdenie a dátum',
      fields: [
        {
          id: 'potvrdeniePravdivosti',
          label: 'Potvrdzujem, že uvedené údaje sú pravdivé a úplné.',
          type: 'consent',
          required: true,
          colSpan: 2,
          helper: 'Potvrdenie nahrádza vlastnoručný podpis na papierovom tlačive.',
          chybaText: 'Potvrďte prosím pravdivosť údajov.',
        },
        {
          id: 'suhlasOsobneUdaje',
          label: 'Súhlasím so spracovaním osobných údajov',
          type: 'consent',
          required: true,
          colSpan: 2,
          text: 'Súhlasím so spracovaním uvedených osobných údajov v zmysle zákona č. 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov na účel spracovania tejto žiadosti v rozsahu poskytnutých údajov.',
          chybaText: 'Bez súhlasu so spracovaním osobných údajov žiadosť odoslať nevieme.',
        },
        {
          id: 'miesto',
          label: 'Miesto',
          type: 'text',
          required: true,
          autofillFrom: 'tenant.nazovKratky',
        },
        { id: 'datum', label: 'Dátum', type: 'date', required: true, autofillFrom: 'dnes' },
      ],
    },
  ],
  prilohy: [
    {
      id: 'kolaudacne-rozhodnutie',
      nazov: 'Právoplatné kolaudačné rozhodnutie',
      povinna: true,
      poznamka: 'Pri stavbách daných do užívania po 1. 1. 1976.',
      visibleIf: { field: 'obdobieUzivania', equals: 'po_1976' },
    },
    { id: 'geometricky-plan', nazov: 'Geometrický plán ku stavbe', povinna: false },
    { id: 'snimka-mapy', nazov: 'Snímka z katastrálnej mapy', povinna: false },
    {
      id: 'nadobudaci-doklad',
      nazov: 'Kúpnopredajná zmluva, osvedčenie o dedičstve alebo darovacia zmluva',
      povinna: true,
      poznamka: 'Predkladá žiadateľ, ktorý nie je stavebníkom budovy.',
      visibleIf: { field: 'ziadatelJeStavebnik', isTruthy: false },
    },
  ],
}
