import type { FormSchema } from './schema'

/**
 * Formulár 1: Žiadosť o povolenie na vjazd podľa zák. č. 160/1996 Zb.
 * Zdroj: docs/forms/formular_obec_Bernolakovo.pdf, strana 1.
 */
export const vjazdForm: FormSchema = {
  id: 'vjazd-160-1996',
  nazov: 'Žiadosť o povolenie na vjazd',
  kratkyPopis:
    'Povolenie na zriadenie vjazdu z pozemku na miestnu komunikáciu vrátane spevnených plôch.',
  kategoria: 'Doprava a komunikácie',
  poplatokEur: 30,
  poplatokPoznamka:
    'Správny poplatok 30 € uhradíte pri podaní. Doklad o úhrade priložíte k žiadosti.',
  odhadovanyCasMin: 8,
  pravnyZaklad: 'zákona č. 160/1996 Zb. v znení neskorších predpisov',
  adresat: 'Obecný úrad',
  pdfNazov: 'ziadost-o-povolenie-na-vjazd',
  infoPoznamka:
    'Povolenie sa vydáva do vlastných rúk žiadateľovi po predložení dokladu o uhradení správneho poplatku.',
  sections: [
    {
      id: 'ziadatel',
      title: 'Žiadateľ',
      description: 'Uveďte údaje osoby, ktorá o povolenie žiada.',
      fields: [
        {
          id: 'typOsoby',
          label: 'Žiadam ako',
          type: 'radio',
          required: true,
          colSpan: 2,
          options: [
            { value: 'fyzicka', label: 'Fyzická osoba' },
            { value: 'pravnicka', label: 'Právnická osoba' },
          ],
        },
        {
          id: 'nazovFirmy',
          label: 'Názov firmy',
          type: 'text',
          required: true,
          colSpan: 2,
          visibleIf: { field: 'typOsoby', equals: 'pravnicka' },
        },
        {
          id: 'ico',
          label: 'IČO',
          type: 'text',
          required: true,
          validate: 'ico',
          helper: 'Osem číslic bez medzier.',
          visibleIf: { field: 'typOsoby', equals: 'pravnicka' },
        },
        { id: 'titul', label: 'Titul', type: 'text', autofillFrom: 'resident.titul' },
        {
          id: 'meno',
          label: 'Meno',
          type: 'text',
          required: true,
          autofillFrom: 'resident.meno',
        },
        {
          id: 'priezvisko',
          label: 'Priezvisko',
          type: 'text',
          required: true,
          autofillFrom: 'resident.priezvisko',
        },
        {
          id: 'adresa',
          label: 'Adresa žiadateľa',
          type: 'address',
          required: true,
          colSpan: 2,
          autofillFrom: 'resident.trvalyPobyt',
          helper: 'Obec, ulica a PSČ podľa trvalého pobytu alebo sídla.',
        },
        {
          id: 'telefon',
          label: 'Telefón',
          type: 'text',
          required: true,
          validate: 'telefon',
          placeholder: '+421 900 000 000',
          autofillFrom: 'resident.telefon',
        },
        {
          id: 'email',
          label: 'E-mail',
          type: 'text',
          required: true,
          validate: 'email',
          autofillFrom: 'resident.email',
        },
      ],
    },
    {
      id: 'stavba',
      title: 'Druh a účel stavby',
      description: 'Označte pozemok, z ktorého vjazd vedie, a miestnu komunikáciu.',
      fields: [
        {
          id: 'nehnutelnost',
          label: 'Vyberte nehnuteľnosť',
          type: 'propertyPicker',
          colSpan: 2,
          helper: 'Údaje o parcele doplníme z vašej nehnuteľnosti. Môžete ich upraviť.',
        },
        {
          id: 'vjazdZParcely',
          label: 'Vjazd z parcely č.',
          type: 'text',
          required: true,
          autofillFrom: 'property.parcelaCislo',
          placeholder: '1234/5',
        },
        {
          id: 'katastralneUzemie',
          label: 'Katastrálne územie',
          type: 'select',
          required: true,
          optionsFromTenant: 'katastralneUzemia',
          autofillFrom: 'property.katastralneUzemie',
        },
        {
          id: 'nazovMk',
          label: 'Názov miestnej komunikácie',
          type: 'text',
          required: true,
          placeholder: 'Hlavná ulica',
          helper: 'Ulica, na ktorú sa vjazd napája.',
        },
        {
          id: 'mkParcela',
          label: 'Parcela č. miestnej komunikácie',
          type: 'text',
          required: true,
          placeholder: '2100/1',
        },
        {
          id: 'ucelStavby',
          label: 'Účel stavby',
          type: 'textarea',
          required: true,
          colSpan: 2,
          maxLength: 500,
          helper: 'Napríklad vjazd k rodinnému domu vrátane spevnenej plochy.',
        },
      ],
    },
    {
      id: 'narusenie',
      title: 'Narušenie povrchu',
      description: 'Pri zjazde bude narušený povrch. Uveďte rozmery v metroch.',
      fields: [
        {
          id: 'rozmerVozovky',
          label: 'Rozmer narušenia vozovky, teda cestného telesa',
          type: 'text',
          required: true,
          placeholder: '4,0 m x 1,5 m',
        },
        {
          id: 'rozmerZelenehoPasu',
          label: 'Rozmer narušenia zeleného pásu',
          type: 'text',
          required: true,
          placeholder: '4,0 m x 2,0 m',
        },
      ],
    },
    {
      id: 'prilohy',
      title: 'Prílohy',
      description: 'Nahrajte doklady k žiadosti. Prijímame formáty PDF, JPG a PNG.',
      fields: [
        {
          id: 'projektovaDokumentacia',
          label: 'Projektová dokumentácia realizovanej stavby a zjazdu, spevnených plôch',
          type: 'file',
          required: true,
          colSpan: 2,
          maxSuborov: 4,
          maxVelkostMb: 5,
          helper: 'Na úrad sa predkladá v dvoch vyhotoveniach.',
        },
        {
          id: 'dokladOUhrade',
          label: 'Doklad o úhrade správneho poplatku 30 €',
          type: 'file',
          required: true,
          colSpan: 2,
          maxSuborov: 2,
          maxVelkostMb: 5,
        },
      ],
    },
    {
      id: 'suhlas',
      title: 'Súhlas a potvrdenie',
      fields: [
        {
          id: 'suhlasOsobneUdaje',
          label: 'Súhlasím so spracovaním osobných údajov',
          type: 'consent',
          required: true,
          colSpan: 2,
          text: 'Súhlasím so spracovaním uvedených osobných údajov v zmysle zákona č. 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov na účel spracovania tejto žiadosti v rozsahu poskytnutých údajov.',
          chybaText: 'Bez súhlasu so spracovaním osobných údajov žiadosť odoslať nevieme.',
        },
        {
          id: 'potvrdeniePravdivosti',
          label: 'Potvrdzujem, že uvedené údaje sú pravdivé a úplné.',
          type: 'consent',
          required: true,
          colSpan: 2,
          helper: 'Potvrdenie nahrádza vlastnoručný podpis na papierovom tlačive.',
          chybaText: 'Potvrďte prosím pravdivosť údajov.',
        },
        {
          id: 'miesto',
          label: 'Miesto',
          type: 'text',
          required: true,
          autofillFrom: 'tenant.nazovKratky',
        },
        { id: 'datum', label: 'Dátum', type: 'date', required: true, autofillFrom: 'dnes' },
      ],
    },
  ],
  prilohy: [
    {
      id: 'projektova-dokumentacia',
      nazov: 'Projektová dokumentácia realizovanej stavby a zjazdu, spevnených plôch',
      povinna: true,
      poznamka: 'Predkladá sa v dvoch vyhotoveniach.',
    },
    {
      id: 'doklad-o-uhrade',
      nazov: 'Doklad o úhrade správneho poplatku 30 €',
      povinna: true,
    },
  ],
}
